"""Feature schema and vectorization for the shared-encoder model family."""

from .feature_schema import (
    DECISION_CONTEXT_REQUEST_TYPES_V2,
    DECISION_CONTEXT_SEMANTIC_ROLES_V2,
    TENSOR_SCHEMA_ID,
    TENSOR_SCHEMA_VERSION,
    CategoricalFeature,
    HashedStringFeature,
    IgnoredFeature,
    NumericFeature,
    RecordFeatureSchema,
    ReferenceFeature,
    TensorFeatureSchema,
    TensorSchemaID,
    TensorSchemaVersion,
    VectorizedCandidate,
    VectorizedDecision,
    VectorizedDecisionContext,
    VectorizedRelationship,
    VectorizedToken,
    expanded_numeric_width,
)

__all__ = [
    "DECISION_CONTEXT_REQUEST_TYPES_V2",
    "DECISION_CONTEXT_SEMANTIC_ROLES_V2",
    "TENSOR_SCHEMA_ID",
    "TENSOR_SCHEMA_VERSION",
    "CategoricalFeature",
    "HashedStringFeature",
    "IgnoredFeature",
    "NumericFeature",
    "RecordFeatureSchema",
    "ReferenceFeature",
    "TensorFeatureSchema",
    "TensorSchemaID",
    "TensorSchemaVersion",
    "VectorizedCandidate",
    "VectorizedDecision",
    "VectorizedDecisionContext",
    "VectorizedRelationship",
    "VectorizedToken",
    "expanded_numeric_width",
]
